"""initial migrations

Revision ID: 6444b788ac19
Revises: 
Create Date: 2023-07-01 22:10:48.613696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6444b788ac19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###
